# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.4
maven_group = net.reversteam.tagfixes
archives_name = tagfixes
enabled_platforms = fabric,forge

mod_id = tagfixes
mod_name = Tag Fixes
mod_description = Adds tags and tag localization for items, blocks and entities missing them across various mods to improve compatibility. Adds tags and tag localization for items, blocks and entities missing them across various mods to improve compatibility.
mod_author = ReversTeam
mod_license = MIT
display_url = https://curseforge.com/minecraft/mc-mods/tag-fixes
credits = Made by Mitemi, Mysticsquire, and Tikup

# Minecraft properties
minecraft_version = 1.20.1

# Dependencies
fabric_loader_version = 0.18.4
fabric_api_version = 0.92.6+1.20.1
forge_version = 1.20.1-47.4.10
