modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="tagfixes"
version="1.0.1"
displayName="Tag Fixes"
displayURL="https://curseforge.com/minecraft/mc-mods/tag-fixes"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="ReversTeam"
description="Adds tags for items, blocks and entities missing them across various mods to improve compatibility."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.tagfixes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration