modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "${mod_license}"

[[mods]]
modId = "tagfixes"
version = "${version}"
displayName = "Tag Fixes"
authors = "${credits}"
description = '''
${mod_description}
'''
#logoFile = ""

[[dependencies.tagfixes]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tagfixes]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "tagfixes.mixins.json"
