name: Publish Minecraft Mod

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Build Mod
        run: ./gradlew build

      - name: Publish mod files
        uses: tristankechlo/publish-mc-mod@v2.0.0
        with:
          mc-version: "1.20.1"
          mod-version: "1.0.6"
          curseforge-id: 1416898
          modrinth-id: "dJZCkoBx"
          version-range: "[1.20.1,1.20.2)"
          version-type: "release"
          loaders: "forge"
          changelog: |
            - Polished some older localizations
            - Added 664 new tag localizations
            - Added support for the following mods: EnderIO, Tempad, Wizards Reborn, ActuallyAdditions, Archeological, BetterArcheology, Biomancy, Bloody Hell, Butchery Lite, ByteBuddies, Eidolon, Etheria, Extractinator, Farmers' Delight, Fishermen's Trap, Fluffy Fur, Goety, Golem Overhaul, Gravel Ores, Hexcasting, Kaleidoscope Doll, Miners Delight, NeepMeat, Ostrea, Quality Tools Forked, Silver Lavender & Necromancy, Sons of Sin, Starcatcher, Steam Powered, ColonyPathingEdition

          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          forge-glob: ./build/libs/*-universal-!(*-dev|*-sources|*-javadoc).jar