name: Publish Minecraft Mod

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Build Mod
        run: ./gradlew build

      - name: Publish mod files
        uses: tristankechlo/publish-mc-mod@v2.0.0
        with:
          mc-version: "1.21.1"
          mod-version: "1.1.0"
          curseforge-id: 1416898
          modrinth-id: "dJZCkoBx"
          version-range: "[1.21.1,1.21.2)"
          version-type: "release"
          loaders: "neoforge"
          changelog: |
            - Added 417 new tag localizations
            - Added full or partial support for the following mods: Ad Astra, Animus, Artificers Armory, Ascendant Arcana, Bloody Hell, Butchery, Concatenated Additions, Dankstorage, DungeonNowLoading, EnemyExpansion, EnhancedCelestialTweaks, Fracture, Goety, Goety Awaken, Macabre, Malum, Modern Industrialization, Modest Mning, Monster Hunter Villagers, Reverse Eon, Spice of Life Valheim Reforged, Spectrum, Subterannean Wilderness Revival, Tetra, Trinkets, Vampirism, Vampires Delight, Weighted Armor, Whaleborne

          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          neoforge-glob: ./build/libs/*-universal-!(*-dev|*-sources|*-javadoc).jar